name: Deploy to Azure App Service

on:
  push:
    branches: [ main, azure-deployment ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test
      
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'bigin-webhook-server'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
        package: .
        
    - name: 'Health Check'
      run: |
        sleep 30
        curl -f https://bigin-webhook-server.azurewebsites.net/health || exit 1
        
    - name: 'Test Webhook Endpoint'
      run: |
        curl -X POST https://bigin-webhook-server.azurewebsites.net/webhook \
          -H "Content-Type: application/json" \
          -d '{"test": "deployment verification"}' \
          --fail-with-body